apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "NewTemplate"
  description: "NewTemplate"
  annotations:
    github.com/project-slug: VladKay/NewApp
    jenkins.io/job-full-name: '/spring-test'
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
