apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testproject"
  description: "testproject"
  annotations:
    github.com/project-slug: VladKay/testproject
    jenkins.io/job-full-name: default:github-demo # use this instead
    grafana/dashboard-selector: synthetic-monitoring
    grafana/alert-label-selector: "namespace=synthetic_monitoring"
    grafana/tag-selector: synthetic-monitoring


    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
